version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      PORT: 3333

  todolistcc:
    build:
      context: C:/Users/bruno/OneDrive/Área de Trabalho/PosFullStack/TCC/todolist-fullstack-main
      dockerfile: C:/Users/bruno/OneDrive/Área de Trabalho/PosFullStack/TCC/todolist-fullstack-main/Dockerfile

    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: todolist
